key = "-- Insert Key Here --"
queryChallengers = False
queryGrandmasters = False
queryMasters = False
queryPlatDiamond = False
getHighPlat = False
getLowPlat = False
getHighGold = False
getLowGold = False
getHighSilver = True
getLowSilver = False
